# Generated by Django 4.2 on 2023-05-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_bb_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
