# Generated by Django 4.2.1 on 2023-05-31 05:01

import bboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_bb_options_alter_bb_order_with_respect_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamKiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название киоска')),
            ],
            options={
                'verbose_name': 'Киоск с мороженным',
                'verbose_name_plural': 'Киоски с мороженным',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('was_born', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Родился')),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
                'ordering': ['-age', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название мороженого')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, validators=[bboard.models.positive_num_validator], verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлено')),
                ('compound', models.TextField(blank=True, default='Секрет фирмы', null=True, verbose_name='Состав')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('kiosk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.icecreamkiosk', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Мороженое',
                'verbose_name_plural': 'Мороженые',
                'ordering': ['-published', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('was_born', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Родился')),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возраст')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
                'ordering': ['-age', 'name'],
            },
        ),
    ]
