# Generated by Django 4.2.1 on 2023-05-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_bb_kind'),
        ('bboard', '0006_icecreamkiosk_parent_icecream_child'),
    ]

    operations = [
    ]
