# Generated by Django 4.2 on 2023-08-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['name'], 'verbose_name': 'Мой Пользователь', 'verbose_name_plural': 'Мои Пользователи'},
        ),
    ]
