# Generated by Django 4.2.4 on 2023-09-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('hide_comments', 'Можно скрывать комментарии'),)},
        ),
    ]
