# Generated by Django 4.2.4 on 2023-08-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_merge_20230531_1118'),
        ('testapp', '0007_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
